[mypy]
ignore_missing_imports = True
mypy_path = tests

[mypy-cogs.*]
disable_error_code = attr-defined, union-attr, call-overload, assignment, arg-type, override

[mypy-tests.test_cli_cog_integration]
disable_error_code = call-arg, arg-type

[mypy-test_cli_cog_integration]
disable_error_code = call-arg, arg-type
